### ISSUE TITLE
Option to use cookie-session.

### ISSUE THREAD

**Issue by ryan-rushton** [SoftwareBrothers/admin-bro-expressjs#30]
We are looking into using Admin Bro and would like the option to be able to use cookie-session over express-session, as client side cookies would be more convenient in our use case.

We are currently implementing our own `buildAuthenticatedRouter` style function to hook into our auth system.

**Comment by wojtek-krysiak** [comment]
closing this one since this is the exact approach I would suggest (writing your buildAuthenticatedRouter implementation). We don't add this to the @admin-bro/express because we would like to stick with one solution (in the end all more complicated use cases requires to write you buildAuthenticatedRouter)
